### ISSUE TITLE
release version 2

### ISSUE THREAD

**Issue by wumpz** [wumpz/java-diff-utils#10]

**Comment by wumpz** [comment]
@ADiex: look here for progress.

**Comment by wumpz** [comment]
release performed, no signing, no maven central, binaries attached

**Comment by ADiex** [comment]
I can not find the binaries for version 2.0. What does "binaries attached" mean?
Tobias <notifications@github.com> hat am 14. August 2017 um 09:31 geschrieben:release performed, no signing, no maven central, binaries attached
