### ISSUE TITLE
DiffRowGenerator should be able to deliver DiffRow list wwithout HTML tags in oldLine and newLine

### ISSUE THREAD

**Issue by ADiex** [wumpz/java-diff-utils#11]
By default DiffRowGenerator.generateDiffRows delivers a List of DiffRow where the oldLine and the newLine property are polluted with HTML tags like <br> and HTML-escaping sequences like &gt. 

It should be possible to get the unmodified text lines back for use in projects where HTML enrichment/escaping is not necessary or useful.

My proposal is to introduce a new property _reportLinesUnWrapped_ which can be set by the DiffRowGenerator.Builder. If this property is set to true the DiffRowGenerator delivers back the original text lines.

Please see the attached source.
[DiffRowGenerator.zip](https://github.com/wumpz/java-diff-utils/files/1231315/DiffRowGenerator.zip)

**Comment by wumpz** [comment]
The tags included can be modified using the builder.

**Comment by wumpz** [comment]
If you look at the examples for markup presentation you will see.

**Comment by ADiex** [comment]
The only way to achieve approximatle what diffRowGenerator.generateDiffRows does is DiffUtils.diff (List <T> original, List <T> revised). But my tests with this method and also your example have shown that it only provides the deltas change, insert, delete, and not the unchanged lines. And it also does not provide the the very good line-wise depiction of original and revised as pointed out in DiffRowGenerator. The initial author of DiffRowGenerator unfortunately mixed HTML presentation issues into the generation of a DiffRow list. The DiffRowGenerator could cover not only the requirement to generate HTML-capable code, but also the output of the pure differences of texts. The few lines of code that I inserted in my suggestion there would reach that goal.
[Unittest.zip](https://github.com/wumpz/java-diff-utils/files/1234047/Unittest.zip)

**Comment by wumpz** [comment]
Ah. Sorry. I missed your point. Sure your flag does make thing easier. At the moment you could simulate it using:

```
DiffRowGenerator generator = DiffRowGenerator.create()
                .columnWidth(Integer.MAX_VALUE)
                .oldTag(f -> "")
                .newTag(f -> "")
                .build();
```

**Comment by rosta** [comment]
There is a use case where the raw value would be useful as well as the formatted value:

I need to filter out certain differences by matching them against a set of regular expressions. These expressions are much easier to specify for the raw text than for the html/markdown formatted text. As such it would be nice to have the possibility to hold the raw texts in the DiffRow

**Comment by wumpz** [comment]
@rosta Could you make a separate issue with an example. I M not sure if I understand your problem.
