### ISSUE TITLE
Diff by phrase functionality?

### ISSUE THREAD

**Issue by Lilykos** [wumpz/java-diff-utils#14]
Thanks a lot for this project. I was wondering if something can be done to achieve the following. Let's say I have 2 versions of a string:

"_J. G. Feldstein, Chair_" and "_T. P. Pastor, Chair_"

When using character level diff, I get this result:
![image](https://user-images.githubusercontent.com/2445433/32599595-5087731e-c53d-11e7-98ae-2e1b078a1dbf.png)

Makes sense, of course, since it diffs by character and keeps all the ones that were there before. Id I diff by word, this happens:
![image](https://user-images.githubusercontent.com/2445433/32599640-6cf96994-c53d-11e7-9347-491b14bb60c9.png)

Again, makes sense. However, this makes it difficult for a user to understand what happens. What would be great is if we could **"whitelist"** a few characters, so that they _don't count on the diff_, and use it in phrase level. So in that case, if we whitelist **whitespace** and **punctuation**, we could get:
![image](https://user-images.githubusercontent.com/2445433/32599827-fd475ce0-c53d-11e7-96ed-0d25142b4a8e.png)

Would this be feasible and/or possible?

**Comment by wumpz** [comment]
That would be possible but needed a change. At the moment there is a SPLIT_PATTERN defined to separate words. This pattern needs to be adjusted, or better a function needs to be injected to do character, word or like you call it phrase processing.

I would suggest an API change that would remove inlineDiffByWord and replace it with some kind of splitFunction to make this completely adjustable or by inlineDiffByPattern and make this SPLIT_PATTERN modifiable.

**Comment by wumpz** [comment]
Please look at DiffRowGeneratorTest.testGeneratorIssue14. Is that what you meant? If I missunderstood you the implemented modifiable splitter is nevertheless a new feature. ;)

The output of this test is:

~J. G. Feldstein~**T. P. Pastor**, Chair

The inline splitter is responsible for splitting the source line into blocks to compare (characters, words, phrases). Its up to you to configure it the way you want it to behave.

**Comment by Lilykos** [comment]
Yes, working nicely! Thanks a lot for your efforts!

**Comment by wumpz** [comment]
By the way. Did you ok know, it's been deployed to maven central?

**Comment by The-Lum** [comment]
Hello @wumpz, and all,

How to make a test similar to: 
https://github.com/java-diff-utils/java-diff-utils/blob/02532a9720a9560e8f3ae039837cf960a6338e3e/java-diff-utils/src/test/java/com/github/difflib/text/DiffRowGeneratorTest.java#L285-L292
In my test, I have always this error:
```cy
error: splitStringPreserveDelimiter(String,Pattern) has protected access in DiffRowGenerator
                        .inlineDiffBySplitter(line -> DiffRowGenerator.splitStringPreserveDelimiter(line, Pattern.compile(",")))
                                                                      ^
```

- How to proper call this method?

Regards.
