### ISSUE TITLE
Insert next to change is not working as expected.

### ISSUE THREAD

**Issue by eaingaran** [wumpz/java-diff-utils#16]
### Expected Behavior
Old : [position: 0, size: 1, lines: [Hello]]
New : [position: 0, size: 1, lines: [Hello World]]
Diff Type : CHANGE

Old : [position: 0, size: 0, lines: []]
New : [position: 1, size: 1, lines: [new]]
Diff Type : INSERT
 
Old : [position: 2, size: 1, lines: [Last]]
New : [position: 3, size: 0, lines: []]
Diff Type : DELETE

### Actual Behavior
Old : [position: 0, size: 1, lines: [Hello]]
New : [position: 0, size: 2, lines: [Hello World, new]]
Diff Type : CHANGE

Old : [position: 2, size: 1, lines: [Last]]
New : [position: 3, size: 0, lines: []]
Diff Type : DELETE

### Steps to Reproduce the Problem

  1.Use original.txt and revised.txt as the input and compute difference using the code given below.

Original.txt
Hello
Hi
Last

Revised.txt
Hello World
new
Hi

Java code

List<String> first = Files.readAllLines(Paths.get("src/main/resources/original.txt"));
List<String> second = Files.readAllLines(Paths.get("src/main/resources/revised.txt"));
Patch<String> diff = DiffUtils.diff(first, second);

for(Delta<String> s : diff.getDeltas())    {
    System.out.println("Old : " + s.getOriginal());
    System.out.println("New : " + s.getRevised());
    System.out.println("Diff Type : " + s.getType());
    System.out.println();
}
 

### Specifications

  - Version: 2.2
  - Platform: Windows
  - Subsystem: Windows 7, JDK 1.8_141 (x64)

**Comment by wumpz** [comment]
The actual behaviour is the expected one. DiffUtils.diff does not work row by row.  You should switch to DiffRowGenerator to get better results.

**Comment by eaingaran** [comment]
Got it. Thanks..
