### ISSUE TITLE
usage: DiffRowGenerator to compute git-diff like diffs?

### ISSUE THREAD

**Issue by surli** [wumpz/java-diff-utils#17]
Hi!

First thanks for this project, it's quite interesting and useful 👍 
I'm trying to use it to compute diff between piece of Java codes and I want to obtain diff like those created by git-diff. The ultimate objective would be to obtain exactly the same, if possible. 

So do you have any hint to achieve this objective?

I started with a very simple solution using `DiffRowGenerator` but maybe there's already something creating to transform a diff-utils patch to a git-patch or something like that?

**Comment by wumpz** [comment]
Using DiffUtils you generate a patch, which is what you want. It's a standard diff like the one of git.

**Comment by wumpz** [comment]
To get a better impression here is a little example:

```Java
ist<String> text1=Arrays.asList("this is a test","a test");
List<String> text2=Arrays.asList("this is a testfile","a test");

//generating diff information.
Patch<String> diff = DiffUtils.diff(text1, text2);

//generating unified diff format
List<String> unifiedDiff = UnifiedDiffUtils.generateUnifiedDiff("original-file.txt", "new-file.txt", text1, diff, 0);

unifiedDiff.forEach(System.out::println);

//importing unified diff format from file or here from memory to a Patch
Patch<String> importedPatch = UnifiedDiffUtils.parseUnifiedDiff(unifiedDiff);

//apply patch to original list
List<String> patchedText = DiffUtils.patch(text1, importedPatch);

System.out.println(patchedText);
```

For a deeper understanding you should look into GenerateUnifiedDiffTest.java. Here a complete roundtrip is tested too. A patch is generated, written as unified diff imported and processed on the original text to get the new text.

**Comment by surli** [comment]
Great thanks! I'll have a look at it
