### ISSUE TITLE
diff have a problem

### ISSUE THREAD

**Issue by yangtuo** [wumpz/java-diff-utils#22]
### Expected Behavior
|original|new|
|--------|---|
|This is a test ~senctence~.|This is a test **for diffutils**.|
||**This is the second line.**|
### Actual Behavior
|original|new|
|--------|---|
|This is a test ~senctence~.|This is a test **for diffutils**.**|
||**This is the second line.**|

             

             DiffRowGenerator generator = DiffRowGenerator.create()
				.showInlineDiffs(true)
				.inlineDiffByWord(true)
				.oldTag(f -> "~")
				.newTag(f -> "**")
				.build();
		List<DiffRow> rows = generator.generateDiffRows(
				Arrays.asList("This is a test senctence."),
				Arrays.asList("This is a test for diffutils.", "This is the second line."));

		System.out.println("|original|new|");
		System.out.println("|--------|---|");
		for (DiffRow row : rows) {
			System.out.println("|" + row.getOldLine() + "|" + row.getNewLine() + "|");
		}

**Comment by wumpz** [comment]
I assume you flipped expected and actual behaviour.

**Comment by wumpz** [comment]
This boils down to the question, if the linefeed should be part of the difference or not. I think it should be part of it, since in your example a newline is introduced. The Arrays have different size. If you start with 

`Arrays.asList("This is a test senctence.","")`

you get your expected behavior.

**Comment by yangtuo** [comment]
thanks ,I want diff two String .

**Comment by yangtuo** [comment]
thanks for the reply,I want to compare the difference between two strings 。
String a = "This is a test senctence."        
String b="This is a test for diffutils.\nThis is the second line." 


```

               DiffRowGenerator generator = DiffRowGenerator.create()
				.showInlineDiffs(true)
				.inlineDiffByWord(true)
				.oldTag(f -> "~")
				.newTag(f -> "**")
				.build();

		String aa = "This is a test senctence.";
		String bb ="This is a test for diffutils.\nThis is the second line.";
		List<DiffRow> rows = generator.generateDiffRows(
				Arrays.asList(aa.split("\n")),
				Arrays.asList(bb.split("\n")));

		System.out.println("|original|new|");
		System.out.println("|--------|---|");
		for (DiffRow row : rows) {
			System.out.println("|" + row.getOldLine() + "|" + row.getNewLine() + "|");
		}
```

**Comment by wumpz** [comment]
I changed my mind. Due to visualization it is clear, that there is a linefeed. And because this line diff is generated for visualiization purposes the result should be the one you expected.

**Comment by wumpz** [comment]
The actual result in version 3.0-SNAPSHOT is

|original|new|
|--------|---|
|This is a test ~senctence~.|This is a test **for diffutils**.|
||**This is the second line.**|
