### ISSUE TITLE
Documenting thread-safety of DiffRowGenerator

### ISSUE THREAD

**Issue by benelog** [wumpz/java-diff-utils#24]
### Expected Behavior
Confirm the thread-safety on javadoc of DiffRowGenerator

### Actual Behavior
Can not find the information about thread-safety  from javadoc

### Steps to Reproduce the Problem
see https://github.com/wumpz/java-diff-utils/blob/master/src/main/java/com/github/difflib/text/DiffRowGenerator.java

  1.
  1.
  1.

### Specifications

  - Version: current version
  - Platform:
  - Subsystem:

**Comment by wumpz** [comment]
DiffRowGenerator should be threadsafe . However it was not intentionally designed so. Creating one is very cheap using the builder, so why reuse the generator between different threads?

**Comment by benelog** [comment]
@wumpz 

I tried not to create DiffRowGenerator every time to reduce the  objects generated as much as possible.
Now, I understand that the cost of the creation of this object is cheap, so I do not need to share it in multi-thread. Thank you.
