### ISSUE TITLE
DiffRow implements Serializable

### ISSUE THREAD

**Issue by ADiex** [wumpz/java-diff-utils#9]
Use of DiffRow generates problems in clustered environments (using Infinispan), because DiffRow is not marked as Serializable, but is IS Serializable. Add ... implements Serializable. See attached code
[DiffRow.zip](https://github.com/wumpz/java-diff-utils/files/1210986/DiffRow.zip)

**Comment by wumpz** [comment]
The first external issue for this repo. 👍

**Comment by ADiex** [comment]
Hello, Tobias;Thank you for your fast reaction. I see that you already have fixed the issue.I was glad to find a living project which continues the java-diff-utils on GitHub.I wanted to contribute the the Serialization change, (using this guide https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/ ), but I am not allowed to push a new branch (403 - Access denied). Now I have two questions (please excuse ;-) )1. Do you plan to make a new release in next time? Our build system does not allow to make releases of projects where snapshot versions are included.2. If you make a release: Is it possible to upload it to the Maven Central repository? Thank you and best regardsAndreas
Tobias <notifications@github.com> hat am 9. August 2017 um 13:00 geschrieben:The first external issue for this repo. 👍

**Comment by wumpz** [comment]
Building a release is not that problematic. To upload it to maven central the way is over sonatype. I did it for e.g. JSqlParser. Its a little bit time consuming. So the first could be done relative quickly.

You are not allowed to make branches in this repository. But if you fork it, then you have a working copy, where you are allowed to do this. Then you can from your fork / branch make pull requests, that I see within my (master) project.

Cheers Tobias

**Comment by wumpz** [comment]
Any comments here? Would a github release be enough? I have a maven_repo here at wumpz/maven_repo.

**Comment by ADiex** [comment]
Yes, a github release would be enough, and a public accessible maven repo would be perfect.I have tried to make a release in a fork (dry run), but I think that would lead to another project. I do not want to fork your project but support your project. And the upload to Maven central repo is much more complicated if I am not the project owner. So if you publish a new release of wumpz/java-diff-utils that would be perfect.
Tobias <notifications@github.com> hat am 11. August 2017 um 10:59 geschrieben:Any comments here? Would a github release be enough? I have a maven_repo here at wumpz/maven_repo.
